"""Ensure created_at defaults at ORM and DB level

Revision ID: 3cbbc30711de
Revises: 947b3fdfbb02
Create Date: 2025-03-04 22:22:46.848926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cbbc30711de'
down_revision: Union[str, None] = '947b3fdfbb02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
